#!/usr/bin/env python3
"""Travel Agent CLI powered by Claude, with Agentic RAG over a policy
knowledge base (cancellation, baggage, insurance).

Run from a terminal:
    python agent-demo2.py

Reads ANTHROPIC_API_KEY, VOYAGE_API_KEY, and KB_INDEX_URL from config.env
(same directory as this script). VOYAGE_API_KEY and KB_INDEX_URL are only
needed for the search_policies tool; run scripts/ingest_knowledge_base.mjs
once to populate KB_INDEX_URL.
"""

import json
import os
import sys
import urllib.request
from pathlib import Path

from dotenv import load_dotenv
import anthropic

# Some Windows terminals default stdout to a legacy codepage (e.g. cp1252)
# that can't encode characters Claude may output (arrows, emoji, curly
# quotes). Force UTF-8 so streaming output never crashes mid-response.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

MODEL = "claude-opus-4-8"
VOYAGE_MODEL = "voyage-3.5"
SCRIPT_DIR = Path(__file__).resolve().parent

SYSTEM_PROMPT = (
    "You are an expert, friendly travel agent. You give concrete, "
    "well-reasoned vacation recommendations and realistic flight guidance. "
    "Use the web_search tool to ground destination and flight information in "
    "current, real data rather than guessing. Use the search_policies tool "
    "whenever the traveler asks about cancellation/refund rules, baggage "
    "allowances or fees, or travel insurance coverage — answer those topics "
    "only from what the tool returns, and say so plainly if the knowledge "
    "base doesn't cover something. Always disclose that flight prices "
    "fluctuate and recommend the traveler confirm final prices before "
    "booking."
)

# Deliberately using the basic web_search_20250305 variant rather than the
# newer dynamic-filtering web_search_20260209: the latter runs code
# execution under the hood, and when our search_policies tool interrupts a
# turn mid-search, the resulting container isn't reliably exposed back to us
# to thread into the next request, so the API 400s with "container_id is
# required when there are pending tool uses generated by code execution...".
# The basic variant has no hidden code-execution container, so it doesn't
# hit this failure mode when mixed with a custom tool loop.
TOOLS = [
    {"type": "web_search_20250305", "name": "web_search", "max_uses": 6},
    {
        "name": "search_policies",
        "description": (
            "Search the travel agency's official cancellation, baggage, and "
            "travel-insurance policy documents. Call this whenever the "
            "traveler asks about cancellation or refund rules, baggage "
            "allowances/fees, or travel insurance coverage, instead of "
            "answering from general knowledge."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "The policy question to search for, e.g. 'refund for "
                        "cancelled flight within 24 hours'"
                    ),
                }
            },
            "required": ["query"],
        },
    },
]


def load_config() -> dict:
    load_dotenv(SCRIPT_DIR / "config.env")
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key or api_key == "your-api-key-here":
        print(
            "No Anthropic API key found.\n"
            f"Add ANTHROPIC_API_KEY=<your key> to {SCRIPT_DIR / 'config.env'} and try again."
        )
        sys.exit(1)
    return {
        "anthropic_api_key": api_key,
        "voyage_api_key": os.environ.get("VOYAGE_API_KEY", "").strip(),
        "kb_index_url": os.environ.get("KB_INDEX_URL", "").strip(),
        "blob_read_write_token": os.environ.get("BLOB_READ_WRITE_TOKEN", "").strip(),
    }


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{prompt}{suffix}: ").strip()
    return answer or default


def collect_trip_info() -> dict:
    print("=" * 60)
    print("  Claude Travel Agent")
    print("=" * 60)
    print("Answer a few questions and I'll put together a vacation plan.")
    print("(Press Enter to skip any question you're not sure about.)\n")

    info = {}
    info["origin"] = ask("Which city/airport will you be traveling from?")
    info["destination"] = ask(
        "Do you have a destination in mind? (leave blank for suggestions)"
    )
    info["region_preference"] = ""
    if not info["destination"]:
        info["region_preference"] = ask(
            "Any preferred region or type of trip? (e.g. beach, Europe, mountains, "
            "anywhere warm)"
        )
    info["travel_dates"] = ask(
        "When do you want to travel? (specific dates or a month/season)"
    )
    info["trip_length"] = ask("How many days is the trip?")
    info["travelers"] = ask("How many travelers (and any kids)?", "1 adult")
    info["budget"] = ask("What's your approximate total budget (per person or total)?")
    info["interests"] = ask(
        "What do you enjoy on vacation? (e.g. relaxing on a beach, hiking, "
        "food & culture, nightlife, adventure sports)"
    )
    info["constraints"] = ask(
        "Any constraints? (e.g. direct flights only, visa-free, pet-friendly, "
        "accessibility needs)"
    )
    return info


def build_prompt(info: dict) -> str:
    lines = ["Plan a vacation based on the following traveler details:"]
    for label, key in [
        ("Departure city/airport", "origin"),
        ("Desired destination", "destination"),
        ("Region/trip-type preference", "region_preference"),
        ("Travel dates", "travel_dates"),
        ("Trip length", "trip_length"),
        ("Travelers", "travelers"),
        ("Budget", "budget"),
        ("Interests", "interests"),
        ("Constraints", "constraints"),
    ]:
        value = info.get(key, "").strip()
        if value:
            lines.append(f"- {label}: {value}")

    lines.append("")
    lines.append(
        "If no destination was given, suggest 2-3 well-matched destinations, ranked, "
        "with a short reason each. If a destination was given, confirm it's a good "
        "fit (or flag concerns) and focus the plan on it."
    )
    lines.append(
        "For the chosen/recommended destination(s), include: best time to visit, "
        "a rough daily/total budget estimate, 3-5 suggested activities matching the "
        "traveler's interests, and any relevant travel advisories or visa notes."
    )
    lines.append(
        "For flights: use web search to find current, realistic flight options from "
        "the departure city, including likely airlines, typical routing (direct vs "
        "connecting), approximate round-trip economy price range, and a suggestion "
        "for where to book (e.g. Google Flights, airline site) with a ready-to-use "
        "search query."
    )
    lines.append(
        "If the traveler's constraints or interests touch on cancellation, baggage, "
        "or travel insurance, use the search_policies tool to ground that part of "
        "the answer in the official policy documents."
    )
    lines.append(
        "Keep the response well-organized with clear headings, and keep it concise "
        "and actionable rather than exhaustive."
    )
    return "\n".join(lines)


# --- Agentic RAG: knowledge-base search backed by Voyage embeddings ---------

_kb_index_cache = None


def voyage_embed(config: dict, text: str, input_type: str = "query") -> list:
    api_key = config["voyage_api_key"]
    if not api_key or api_key == "your-voyage-api-key-here":
        raise RuntimeError(
            f"VOYAGE_API_KEY is not set. Add it to {SCRIPT_DIR / 'config.env'}."
        )

    payload = json.dumps(
        {"model": VOYAGE_MODEL, "input": [text], "input_type": input_type}
    ).encode("utf-8")
    req = urllib.request.Request(
        "https://api.voyageai.com/v1/embeddings",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["data"][0]["embedding"]


def load_kb_index(config: dict) -> list:
    global _kb_index_cache
    if _kb_index_cache is not None:
        return _kb_index_cache

    url = config["kb_index_url"]
    if not url:
        raise RuntimeError(
            f"KB_INDEX_URL is not set. Run scripts/ingest_knowledge_base.mjs and "
            f"add the resulting URL to {SCRIPT_DIR / 'config.env'}."
        )

    # The Blob store is private, so reads need the read-write token sent as
    # a bearer token, same as the Vercel Blob SDK does internally.
    token = config.get("blob_read_write_token", "")
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        _kb_index_cache = json.loads(resp.read().decode("utf-8"))
    return _kb_index_cache


def cosine_similarity(a: list, b: list) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(y * y for y in b) ** 0.5
    if not norm_a or not norm_b:
        return 0.0
    return dot / (norm_a * norm_b)


def search_policies(config: dict, query: str, top_k: int = 4) -> str:
    query_embedding = voyage_embed(config, query, "query")
    index = load_kb_index(config)

    scored = sorted(
        (
            (chunk, cosine_similarity(query_embedding, chunk["embedding"]))
            for chunk in index
        ),
        key=lambda pair: pair[1],
        reverse=True,
    )[:top_k]

    if not scored:
        return "No matching policy information found."

    return "\n\n---\n\n".join(
        f"[{chunk['source']} — {chunk['heading']}] (relevance {score:.2f})\n{chunk['text']}"
        for chunk, score in scored
    )


# --- Agent loop --------------------------------------------------------------


def run_agent_turn(client: anthropic.Anthropic, messages: list, container_id: str | None):
    """Stream one turn to stdout and return the final Message."""
    kwargs = dict(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        thinking={"type": "adaptive"},
        output_config={"effort": "medium"},
        tools=TOOLS,
        messages=messages,
    )
    if container_id:
        kwargs["container"] = container_id
    with client.messages.stream(**kwargs) as stream:
        for text in stream.text_stream:
            print(text, end="", flush=True)
        return stream.get_final_message()


def run_agent_loop(
    client: anthropic.Anthropic,
    config: dict,
    messages: list,
    container_id: str | None = None,
) -> tuple[list, str | None]:
    """Runs turns (streaming + tool execution) until Claude stops calling
    search_policies. Returns the updated messages list and container id so
    callers can keep the conversation going across follow-up questions.

    The container id threads through web_search's server-side dynamic
    filtering (which runs code execution under the hood): if our
    search_policies tool interrupts a turn that has pending container-bound
    tool use, resuming the conversation requires re-sending that same
    container id, or the API returns a 400.
    """
    for _ in range(5):
        final = run_agent_turn(client, messages, container_id)

        if final.container:
            container_id = final.container.id

        if final.stop_reason == "refusal":
            print("\n\nClaude declined to respond to this request.")
            return messages, container_id

        messages.append({"role": "assistant", "content": final.content})

        if final.stop_reason != "tool_use":
            print()
            return messages, container_id

        tool_uses = [
            block
            for block in final.content
            if block.type == "tool_use" and block.name == "search_policies"
        ]
        if not tool_uses:
            print()
            return messages, container_id

        tool_results = []
        for tool_use in tool_uses:
            query = tool_use.input.get("query", "")
            try:
                result_text = search_policies(config, query)
            except Exception as exc:
                result_text = f"Error searching policies: {exc}"
            tool_results.append(
                {
                    "type": "tool_result",
                    "tool_use_id": tool_use.id,
                    "content": result_text,
                }
            )
        messages.append({"role": "user", "content": tool_results})

    print("\n[Stopped after multiple tool calls]")
    return messages, container_id


def main() -> None:
    config = load_config()
    client = anthropic.Anthropic(api_key=config["anthropic_api_key"])

    try:
        info = collect_trip_info()
    except (KeyboardInterrupt, EOFError):
        print("\nCancelled.")
        sys.exit(0)

    if not info.get("origin") and not info.get("destination"):
        print("\nI need at least a departure city or a destination to help. Bye!")
        sys.exit(1)

    print(
        "\nWorking on your vacation plan (this can take a bit while I check "
        "flights, destinations, and policies)...\n"
    )

    try:
        messages = [{"role": "user", "content": build_prompt(info)}]
        messages, container_id = run_agent_loop(client, config, messages)

        while True:
            try:
                question = input(
                    "\nAsk a follow-up question, e.g. about cancellation, baggage, "
                    "or insurance (or press Enter to quit): "
                ).strip()
            except (KeyboardInterrupt, EOFError):
                print()
                break
            if not question:
                break
            print()
            messages.append({"role": "user", "content": question})
            messages, container_id = run_agent_loop(client, config, messages, container_id)
    except anthropic.AuthenticationError:
        print("Authentication failed. Check your ANTHROPIC_API_KEY in config.env.")
        sys.exit(1)
    except anthropic.RateLimitError:
        print("\nRate limited by the API. Please wait a moment and try again.")
        sys.exit(1)
    except anthropic.APIStatusError as e:
        print(f"\nAPI error ({e.status_code}): {e.message}")
        sys.exit(1)
    except anthropic.APIConnectionError:
        print("\nCouldn't reach the Anthropic API. Check your internet connection.")
        sys.exit(1)


if __name__ == "__main__":
    main()
