import Anthropic from "@anthropic-ai/sdk";
import { get as getBlob } from "@vercel/blob";

// Shared logic for the travel agent: prompt building, tool definitions, the
// Voyage-backed knowledge-base search (RAG), and the agentic tool-use loop.
// Used by both app/api/plan/route.ts (initial vacation plan) and
// app/api/chat/route.ts (follow-up questions, e.g. about cancellation,
// baggage, or insurance policy).

export const MODEL = "claude-opus-4-8";
export const VOYAGE_MODEL = "voyage-3.5";

export interface TripInfo {
  origin?: string;
  destination?: string;
  region_preference?: string;
  travel_dates?: string;
  trip_length?: string;
  travelers?: string;
  budget?: string;
  interests?: string;
  constraints?: string;
}

export interface Turn {
  role: "user" | "assistant";
  text: string;
}

const FIELDS: Array<[string, keyof TripInfo]> = [
  ["Departure city/airport", "origin"],
  ["Desired destination", "destination"],
  ["Region/trip-type preference", "region_preference"],
  ["Travel dates", "travel_dates"],
  ["Trip length", "trip_length"],
  ["Travelers", "travelers"],
  ["Budget", "budget"],
  ["Interests", "interests"],
  ["Constraints", "constraints"],
];

export function buildPlanningPrompt(info: TripInfo): string {
  const lines: string[] = ["Plan a vacation based on the following traveler details:"];

  for (const [label, key] of FIELDS) {
    const value = (info[key] ?? "").trim();
    if (value) lines.push(`- ${label}: ${value}`);
  }

  lines.push("");
  lines.push(
    "If no destination was given, suggest 2-3 well-matched destinations, ranked, " +
      "with a short reason each. If a destination was given, confirm it's a good " +
      "fit (or flag concerns) and focus the plan on it."
  );
  lines.push(
    "For the chosen/recommended destination(s), include: best time to visit, " +
      "a rough daily/total budget estimate, 3-5 suggested activities matching the " +
      "traveler's interests, and any relevant travel advisories or visa notes."
  );
  lines.push(
    "For flights: use web search to find current, realistic flight options from " +
      "the departure city, including likely airlines, typical routing (direct vs " +
      "connecting), approximate round-trip economy price range, and a suggestion " +
      "for where to book (e.g. Google Flights, airline site) with a ready-to-use " +
      "search query."
  );
  lines.push(
    "If the traveler's constraints or interests touch on cancellation, baggage, " +
      "or travel insurance, use the search_policies tool to ground that part of " +
      "the answer in the official policy documents."
  );
  lines.push(
    "Keep the response well-organized with clear headings, and keep it concise " +
      "and actionable rather than exhaustive."
  );

  return lines.join("\n");
}

export function buildFollowUpPrompt(history: Turn[], question: string): string {
  const transcript = history
    .map((turn) => `${turn.role === "user" ? "Traveler" : "Travel Agent"}: ${turn.text}`)
    .join("\n\n");

  return (
    `Here is the conversation so far:\n\n${transcript}\n\n` +
    `Traveler's new question: ${question}\n\n` +
    "Answer the traveler's new question directly, using the earlier context above " +
    "as needed. If it relates to cancellation/refunds, baggage, or travel " +
    "insurance, use the search_policies tool to ground your answer in the " +
    "official policy documents rather than answering from general knowledge."
  );
}

export const SYSTEM_PROMPT =
  "You are an expert, friendly travel agent. You give concrete, well-reasoned " +
  "vacation recommendations and realistic flight guidance. Use the web_search " +
  "tool to ground destination and flight information in current, real data " +
  "rather than guessing. Use the search_policies tool whenever the traveler " +
  "asks about cancellation/refund rules, baggage allowances or fees, or travel " +
  "insurance coverage — answer those topics only from what the tool returns, " +
  "and say so plainly if the knowledge base doesn't cover something. Always " +
  "disclose that flight prices fluctuate and recommend the traveler confirm " +
  "final prices before booking.";

// Tools available to the agent. web_search is a server-side tool (handled
// automatically by Anthropic within one turn); search_policies is a
// client-side custom tool we execute ourselves (see runAgentLoop below).
//
// Deliberately using the basic web_search_20250305 variant rather than the
// newer dynamic-filtering web_search_20260209: the latter runs code
// execution under the hood, and when our search_policies tool interrupts a
// turn mid-search, the resulting container isn't reliably exposed back to
// us to thread into the next request — the API then 400s with "container_id
// is required when there are pending tool uses generated by code
// execution...". The basic variant has no hidden code-execution container,
// so it doesn't hit this failure mode when mixed with a custom tool loop.
export const TOOLS: Anthropic.Messages.ToolUnion[] = [
  { type: "web_search_20250305", name: "web_search", max_uses: 6 },
  {
    name: "search_policies",
    description:
      "Search the travel agency's official cancellation, baggage, and travel-insurance " +
      "policy documents. Call this whenever the traveler asks about cancellation or refund " +
      "rules, baggage allowances/fees, or travel insurance coverage, instead of answering " +
      "from general knowledge.",
    input_schema: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description:
            "The policy question to search for, e.g. 'refund for cancelled flight within 24 hours'",
        },
      },
      required: ["query"],
    },
  },
];

interface KBChunk {
  id: string;
  source: string;
  heading: string;
  text: string;
  embedding: number[];
}

let cachedIndex: KBChunk[] | null = null;

const KB_INDEX_PATHNAME = "knowledge-base/index.json";

async function loadKnowledgeBaseIndex(): Promise<KBChunk[]> {
  if (cachedIndex) return cachedIndex;

  // The Blob store is private, so reads (like uploads) need the read-write
  // token — a plain public fetch() won't work. The SDK resolves the full
  // blob URL itself from the pathname + token, so KB_INDEX_URL isn't needed.
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      "BLOB_READ_WRITE_TOKEN is not set. It's required to read the private " +
        "knowledge-base Blob store."
    );
  }

  const result = await getBlob(KB_INDEX_PATHNAME, { access: "private", token });
  if (!result) {
    throw new Error(
      "Knowledge base index not found in Blob storage. Run the ingestion script first."
    );
  }

  const text = await new Response(result.stream).text();
  cachedIndex = JSON.parse(text) as KBChunk[];
  return cachedIndex;
}

export async function embedText(
  text: string,
  inputType: "query" | "document" = "query"
): Promise<number[]> {
  const apiKey = process.env.VOYAGE_API_KEY;
  if (!apiKey) {
    throw new Error("VOYAGE_API_KEY is not set.");
  }

  const res = await fetch("https://api.voyageai.com/v1/embeddings", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ model: VOYAGE_MODEL, input: [text], input_type: inputType }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Voyage embeddings request failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { data: { embedding: number[] }[] };
  return data.data[0].embedding;
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

export async function searchPolicies(query: string, topK = 4): Promise<string> {
  const [queryEmbedding, index] = await Promise.all([
    embedText(query, "query"),
    loadKnowledgeBaseIndex(),
  ]);

  const scored = index
    .map((chunk) => ({ chunk, score: cosineSimilarity(queryEmbedding, chunk.embedding) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, topK);

  if (scored.length === 0) {
    return "No matching policy information found.";
  }

  return scored
    .map(
      ({ chunk, score }) =>
        `[${chunk.source} — ${chunk.heading}] (relevance ${score.toFixed(2)})\n${chunk.text}`
    )
    .join("\n\n---\n\n");
}

// Runs the agentic tool-use loop for a single user prompt: streams assistant
// text as it's generated, and whenever Claude calls search_policies, executes
// it locally and feeds the result back for another turn. Stops on end_turn,
// refusal, or after a small number of tool-use rounds (safety cap).
export function runAgentLoop(promptText: string): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();

  return new ReadableStream<Uint8Array>({
    async start(controller) {
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        controller.enqueue(encoder.encode("Server is missing ANTHROPIC_API_KEY."));
        controller.close();
        return;
      }

      const client = new Anthropic({ apiKey });
      const messages: Anthropic.MessageParam[] = [{ role: "user", content: promptText }];
      // Server-side tools (web_search's dynamic filtering) run code execution
      // under the hood and can leave a pending container-bound tool use when
      // our own tool_use interrupts the turn. Continuing that conversation
      // requires re-sending the same container id, or the API 400s with
      // "container_id is required when there are pending tool uses...".
      let containerId: string | undefined;

      try {
        for (let iteration = 0; iteration < 5; iteration++) {
          const claudeStream = client.messages.stream({
            model: MODEL,
            max_tokens: 4096,
            system: SYSTEM_PROMPT,
            thinking: { type: "adaptive" },
            output_config: { effort: "medium" },
            tools: TOOLS,
            messages,
            ...(containerId ? { container: containerId } : {}),
          });

          claudeStream.on("text", (delta) => {
            controller.enqueue(encoder.encode(delta));
          });

          const final = await claudeStream.finalMessage();

          if (final.container?.id) {
            containerId = final.container.id;
          }

          if (final.stop_reason === "refusal") {
            controller.enqueue(
              encoder.encode("\n\nClaude declined to respond to this request.")
            );
            break;
          }

          if (final.stop_reason !== "tool_use") {
            break;
          }

          const policyToolUses = final.content.filter(
            (block): block is Anthropic.ToolUseBlock =>
              block.type === "tool_use" && block.name === "search_policies"
          );

          if (policyToolUses.length === 0) {
            // Nothing for us to execute (e.g. only server-side web_search
            // activity happened) — avoid looping forever.
            break;
          }

          messages.push({ role: "assistant", content: final.content });

          const toolResults: Anthropic.ToolResultBlockParam[] = [];
          for (const toolUse of policyToolUses) {
            const input = toolUse.input as { query?: string };
            const query = typeof input.query === "string" ? input.query : "";
            let resultText: string;
            try {
              resultText = await searchPolicies(query);
            } catch (err) {
              resultText = `Error searching policies: ${
                err instanceof Error ? err.message : String(err)
              }`;
            }
            toolResults.push({
              type: "tool_result",
              tool_use_id: toolUse.id,
              content: resultText,
            });
          }
          messages.push({ role: "user", content: toolResults });
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : "Unknown error";
        controller.enqueue(encoder.encode(`\n\n[Error: ${message}]`));
      } finally {
        controller.close();
      }
    },
  });
}
